server:
  port: 9090
  compression:
    enabled: true
    min-response-size: 2048
    # Comma-separated list of MIME types that should be compressed.
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/xml,application/javascript
  servlet:
    contextPath: /
    session:
      timeout: 1h
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/digital?useSSL=false
    password: 'devteam'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

