server:
  port: 9090
  compression:
    enabled: true
    min-response-size: 2048
    # Comma-separated list of MIME types that should be compressed.
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/xml,application/javascript
  servlet:
    contextPath: /
    session:
      timeout: 1h
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

spring:
  datasource:
    username: zosypussmbaoad
    url: jdbc:postgresql://ec2-52-201-168-60.compute-1.amazonaws.com:5432/d60e6vvl8t7lq9
    password: 499a656f84716503c288c6ed799b6b0e2f05c6b98bfb52af7a1477a12a4c63a1
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

